stages:
  - build
  - deploy

variables:
# System environment

  # Common parameters for the 'make' during CI tests
  MAKEFLAGS: "-j5 --no-keep-going"

# GitLab-CI environment

  # more attempts for more robust
  GET_SOURCES_ATTEMPTS: "10"
  ARTIFACT_DOWNLOAD_ATTEMPTS: "10"

  # We use get_sources.sh script to fetch the submodules and/or re-fetch the repo
  # if it was corrupted (if submodule update fails this can happen)
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: none
  MDF_PATH: "$CI_PROJECT_DIR"
  IDF_PATH: "$CI_PROJECT_DIR/esp-idf"

.setup_tools_unless_target_test: &setup_tools_unless_target_test |
  if [ "$CI_JOB_STAGE" != "target_test" ]; then
  tools/idf_tools.py --non-interactive install && eval "$(tools/idf_tools.py --non-interactive export)" || exit 1
  fi

before_script:
  # - export PATH="/opt/xtensa-esp32-elf/bin:$PATH"
  - export PATH="/opt/esp32ulp-elf-binutils/bin:$PATH"
  - export PATH="$MDF_PATH/esp-idf/tools:$PATH"
  # add gitlab ssh key
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -n $GITLAB_KEY > ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # replace submodule esp-idf to internal repository to speedup cloning
  - sed -i "s%https://github.com/espressif/esp-idf.git%${GITLAB_SSH_SERVER}/idf/esp-idf.git%" .gitmodules
  - git submodule update --init --recursive
  - source esp-idf/tools/ci/setup_python.sh
  # (the same regular expressions are used to set these are used in 'only:' sections below
  - source esp-idf/tools/ci/configure_ci_environment.sh
  - *setup_tools_unless_target_test

.build_template: &build_template
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-ci-env$BOT_DOCKER_IMAGE_TAG
  tags:
    - build
  variables:
    ARTIFACTS_NAME: "default"
    DEFAULT_CONFIG: ""
    BATCH_BUILD: "1"
    V: "0"
  artifacts:
    when: always
    paths:
      - sdkconfig
      - build/*.bin
      - build/*.elf
      - build/*.map
      - build/bootloader/*.bin
      - build/download.config
    expire_in: 1 month
    name: $ARTIFACTS_NAME
  script:
    - cd $EXAMPLE_PATH
    - make defconfig
    - make -j5
    - make print_flash_cmd | tail -n 1 > build/download.config
    #- idf.py defconfig
    - idf.py build

build_example_get_started:
  <<: *build_template
  variables:
    ARTIFACTS_NAME: "get-started"
    EXAMPLE_PATH: "examples/get-started"

build_example_mconfig:
  <<: *build_template
  variables:
    ARTIFACTS_NAME: "mconfig"
    EXAMPLE_PATH: "examples/function_demo/mconfig"

build_example_mupgrade:
  <<: *build_template
  variables:
    ARTIFACTS_NAME: "mupgrade"
    EXAMPLE_PATH: "examples/function_demo/mupgrade"

build_example_mwifi_router:
  <<: *build_template
  variables:
    ARTIFACTS_NAME: "mwifi"
    EXAMPLE_PATH: "examples/function_demo/mwifi/router"

build_example_mwifi_norouter:
  <<: *build_template
  variables:
    ARTIFACTS_NAME: "mwifi"
    EXAMPLE_PATH: "examples/function_demo/mwifi/no_router"

build_example_mwifi_console_test:
  <<: *build_template
  variables:
    ARTIFACTS_NAME: "mwifi"
    EXAMPLE_PATH: "examples/function_demo/mwifi/console_test"

build_example_mwifi_mqtt_example:
  <<: *build_template
  variables:
    ARTIFACTS_NAME: "mwifi"
    EXAMPLE_PATH: "examples/function_demo/mwifi/mqtt_example"

build_example_mwifi_ethernet_example:
  <<: *build_template
  variables:
    ARTIFACTS_NAME: "mwifi"
    EXAMPLE_PATH: "examples/function_demo/mwifi/root_on_ethernet"

build_example_mcommon:
  <<: *build_template
  variables:
    ARTIFACTS_NAME: "mcommon"
    EXAMPLE_PATH: "examples/function_demo/mcommon"

build_example_light:
  <<: *build_template
  variables:
    ARTIFACTS_NAME: "light"
    EXAMPLE_PATH: "examples/development_kit/light"

build_example_button:
  <<: *build_template
  variables:
    ARTIFACTS_NAME: "button"
    EXAMPLE_PATH: "examples/development_kit/button"

build_example_buddy:
  <<: *build_template
  variables:
    ARTIFACTS_NAME: "buddy"
    EXAMPLE_PATH: "examples/development_kit/buddy"

push_master_to_github:
  stage: deploy
  only:
    - master
    - /^release\/v/
#  when: on_success
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  variables:
    GIT_STRATEGY: clone
    GITHUB_PUSH_REFS: refs/remotes/origin/release refs/remotes/origin/master
  before_script:
    - echo "skip default before_script"
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GH_PUSH_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git remote add github git@github.com:espressif/esp-mdf.git
    # What the next line of script does: goes through the list of refs for all branches we push to github,
    # generates a snippet of shell which is evaluated. The snippet checks CI_BUILD_REF against the SHA
    # (aka objectname) at tip of each branch, and if any SHAs match then it checks out the local branch
    # and then pushes that ref to a corresponding github branch
    #
    # NB: In gitlab 9.x, CI_BUILD_REF was deprecated. New name is CI_COMMIT_REF. If below command suddenly
    # generates bash syntax errors, this is probably why.
    - eval $(git for-each-ref --shell bash --format 'if [ $CI_BUILD_REF == %(objectname) ]; then git checkout -B %(refname:strip=3); git push --follow-tags github %(refname:strip=3); fi;' $GITHUB_PUSH_REFS)


# If you want to add new build example jobs, please add it into dependencies of `.example_test_template`

build_docs:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-ci-env$BOT_DOCKER_IMAGE_TAG
  tags:
    - build_docs
  artifacts:
    when: always
    paths:
      # English version of documentation
      - docs/en/doxygen-warning-log.txt
      - docs/en/sphinx-warning-log.txt
      - docs/en/sphinx-warning-log-sanitized.txt
      - docs/en/_build/html
      # Chinese version of documentation
      - docs/zh_CN/doxygen-warning-log.txt
      - docs/zh_CN/sphinx-warning-log.txt
      - docs/zh_CN/sphinx-warning-log-sanitized.txt
      - docs/zh_CN/_build/html
    expire_in: 1 mos
  script:
    - cd docs
    - ./check_lang_folder_sync.sh
    - cd en
    - make gh-linkcheck
    - make html
    - ../check_doc_warnings.sh
    - cd ../zh_CN
    - make gh-linkcheck
    - make html
    - ../check_doc_warnings.sh
